### ISSUE TITLE
[Arsenal] Incompatability with "Truly Modular:Arsenal"

### ISSUE THREAD

**Issue by JadeHeartDeer** [doctor4t/Issues#13]
Hello im here to report an issue with the mod Arsenal, and it's incompatibility with the mod "Truly Modular: Arsenal" as the mods both have the exact same ModIDs. this can cause the game to not run due to said conflicts. This could become an issue alongside other mods with the name "Arsenal" as we are unsure of their ModIDs.
![Screenshot_20241212_195212_Discord](https://github.com/user-attachments/assets/c04cbb6e-d3f2-482c-9ad1-bf6da9991f0d)
![Screenshot_20241212_195251_Discord](https://github.com/user-attachments/assets/34f66eef-8a61-4b43-807a-4b8551c8d34a)

**Comment by doctor4t** [comment]
I can't really fix that. I have the slug "arsenal" on Modrinth, and I've always used it, so I'm not planning to change it.
