### ISSUE TITLE
[Arsenal] using normal hotkey to swap from backslot slot to previous hotbar slot not working, only the arsenal hotkey works

### ISSUE THREAD

**Issue by medecoole** [doctor4t/Issues#3]
[how to recreate] put item in backslot, swap to holding it (lets say we were on hotbar slot 2 while doing this), use a hotkey to swap back (lets say if you use "2" for hotbar slot 2, press 2), this doesnt work, only the hotkey for swapping between backslot and hotbar works (idk if this is intensional or not)

**Comment by doctor4t** [comment]
Works fine on 0.1.3
