### ISSUE TITLE
[Arsenal] Anchorblade can only be reeled in with another Anchorblade in hand

### ISSUE THREAD

**Issue by BlueIsADude** [doctor4t/Issues#32]
As of the latest version (0.1.5), you can't reel in your anchorblade unless you have another anchorblade in your offhand.

https://github.com/user-attachments/assets/70595350-52f0-4552-99a6-72a0df3c94f8

Tested this with just Arsenal, Fabric API, and Ratatouille installed. 
Sorry if the recording is a bit laggy and shaky, my computer is old and i was spamming right-click a ton.

**Comment by Winman7486** [comment]
I put this in https://github.com/doctor4t/Issues/issues/18 already lol

**Comment by BlueIsADude** [comment]
oh oops
