### ISSUE TITLE
[Arsenal] (Not Priority) Swords inside of the Weapon Rack aren't held by the hilt.

### ISSUE THREAD

**Issue by AstralButOnGitHub** [doctor4t/Issues#35]
![2024-12-20_07 59 45](https://github.com/user-attachments/assets/779047c8-8de1-4bdb-af90-1cab26d5e4cc)
POV You're a mimic disguising as a sword:

**Comment by doctor4t** [comment]
Sword is centered and meant to be displayed upside down held by the guard, works as intended
