### ISSUE TITLE
[Arsenal] Enchanting with Enchancement bug

### ISSUE THREAD

**Issue by PunchmadeDav** [doctor4t/Issues#39]
When enchanting weapons they require multiple of the same weapon to enchant. 
![image](https://github.com/user-attachments/assets/ee6e042d-f98a-4e9e-a303-db34aed5ea5a)

**Comment by Winman7486** [comment]
Which version are you using? For me it costs iron ingots

**Comment by PunchmadeDav** [comment]
> Which version are you using? For me it costs iron ingots

1.20-26

**Comment by Winman7486** [comment]
Whats the arsenal version?

**Comment by PunchmadeDav** [comment]
0.1.4

**Comment by Winman7486** [comment]
When you make a new issue you should be basing it off of the newest version, which is currently 0.1.5

**Comment by PunchmadeDav** [comment]
i didnt even see that a new version came out. my bad
