### ISSUE TITLE
[Arsenal] BackSlot Widget is slightly darker than the Offhand One

### ISSUE THREAD

**Issue by Powercyphe** [doctor4t/Issues#4]
![image](https://github.com/user-attachments/assets/011053b9-f44a-4b9a-b002-c32f9c9b2280)

**Reproduction**:
1. Load your game with Arsenal installed
2. Equip a BackSlot Item

**Expected**: The Widget for it is the same as the offhand

**Actual Result**: It is slightly darker

**Potential Fix:**
This is most likely an issue caused by where the Widget Render was injected (if it even uses Mixins) and can get fixed by injecting like this instead: 
`@Inject(method = "renderHotbar", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/util/math/MatrixStack;translate(FFF)V", shift = At.Shift.AFTER))`

**Comment by doctor4t** [comment]
Not a mixin order issue, Amy just forgot the blend function. Thanks for the suggestion though!
