### ISSUE TITLE
[Arsenal] "Right-click to reel in instantly" with anchor blade is non-functional

### ISSUE THREAD

**Issue by cathoderaykobold** [doctor4t/Issues#43]
Mod loader: Quilt 0.9.2 universal jar
Platform: Windows 10
Mods installed during reproduction: Arsenal, Ratatoille, QFAPI (Quilt Fabric API)
In the video, you demonstrate right-clicking mid-throw to reel the anchor blade in immediately. This does not function in the released version of the mod, making elytra flight incredibly difficult. This is also mentioned by Sneahn in [https://github.com/doctor4t/Issues/issues/40](url).

**Comment by Winman7486** [comment]
This is already put here: https://github.com/doctor4t/Issues/issues/18
