### ISSUE TITLE
[Arsenal] Anchorblade/Scythe render crash when using Perception enchantment from Enchancement

### ISSUE THREAD

**Issue by notNoita** [doctor4t/Issues#7]
Basically, using Enchancement's Perception enchantment and looking at a Drowned holding an Anchorblade or a Vindicator holding a Scythe behind a wall (due to the enchantment's perk of making entities glow behind walls) will crash the game due to the weapons' rendering.

This is a pretty simple crash to reproduce, as it only needs Enchancement and Arsenal.

- Step 1: Enchant any helmet with Perception and wear it
- Step 2: Build a small wall to block view of the Drowned/Vindicator
- Step 3: Spawn a Drowned/Vindicator holding their weapons (in case of Vindicator, it might need an extra player or entity for it to attack)
- Step 4: Go through the wall, and crash

Here's my latest crash log: https://mclo.gs/g0LF4DD

**Comment by doctor4t** [comment]
Doesn't happen in 0.1.3, you're on 0.1.1. Please update Arsenal and only report bugs happening in the latest version in the future, thanks.

**Comment by notNoita** [comment]
Oh! Thank you for fixing that, I didn't even know it was fixed. Sorry 😓😓
